apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gdkuxj6ol-java-springboot
  janus-idp.io/tekton: gdkuxj6ol-java-springboot
  backstage.io/kubernetes-id: gdkuxj6ol-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gdkuxj6ol-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
